#pragma once

using namespace ATL;

template <class T>
class CProxy_ISimpleComEvents : public IConnectionPointImpl<T, &__uuidof( _ISimpleComEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
